maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(4000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 25)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 50)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(3000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 25)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 50)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(3000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 25)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(3000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 25)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(4000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 25)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
maqueen.motorStop(maqueen.Motors.All)
basic.forever(function () {
	
})
